apiVersion: apps/v1
kind: Deployment
metadata:
   name: keeper
   labels:
      app: keeper
spec:
    replicas: 1
    selector:
      matchLabels:
        app: keeper
    template:
      metadata:
        labels:
          app: keeper
      spec:
        containers:
        - name: keeper
          image: komalreddyk/keeperrepo:keeper_app
          ports:
          - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata: 
  name: keeper-service
spec:
  selector:
    app : keeper
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
    

    
   
